name: 'Check Approvals and Workflow Status'
description: 'Checks if all required reviewers approved the PR and another workflow passed.'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: 'node20'
  main: '../../scripts/checkApprovals.js'